# Generated by Django 4.0 on 2022-01-09 15:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('audios', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='audio',
            old_name='Description',
            new_name='description',
        ),
    ]
