# Generated by Django 4.0 on 2022-01-11 10:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('audios', '0002_rename_description_audio_description'),
    ]

    operations = [
        migrations.RenameField(
            model_name='audio',
            old_name='description',
            new_name='Description',
        ),
    ]
