# Generated by Django 4.0 on 2022-01-13 06:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('audios', '0003_rename_description_audio_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='audio',
            name='name',
            field=models.TextField(blank=True, null=True),
        ),
    ]
