# Generated by Django 4.0 on 2022-01-11 10:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('channels', '0002_initial'),
        ('ratings', '0001_initial'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='rating',
            name='Rating',
        ),
        migrations.RemoveField(
            model_name='rating',
            name='audio_id',
        ),
        migrations.AddField(
            model_name='rating',
            name='channel_id',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='channels.channel'),
        ),
        migrations.AddConstraint(
            model_name='rating',
            constraint=models.UniqueConstraint(fields=('channel_id', 'user_id'), name='Rating'),
        ),
    ]
