# Generated by Django 4.0 on 2022-01-11 10:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('channels', '0002_initial'),
        ('ratings', '0002_remove_rating_rating_remove_rating_audio_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rating',
            name='channel_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='channels.channel'),
        ),
    ]
