# Generated by Django 4.0 on 2021-12-14 20:14

import channels.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Channel',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('channel_name', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('profile_pic', models.ImageField(default='media\\channel.png', upload_to=channels.models.upload_to)),
            ],
        ),
        migrations.CreateModel(
            name='Subscribe',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('notification', models.BooleanField(default=True, null=True)),
                ('channel_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='channels.channel')),
            ],
        ),
    ]
