# Generated by Django 4.0 on 2022-01-11 12:28

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('channels', '0004_alter_channel_rate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='channel',
            name='rate',
            field=models.PositiveIntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(5)]),
        ),
    ]
