# Generated by Django 4.0 on 2022-01-12 21:36

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('channels', '0005_alter_channel_rate'),
    ]

    operations = [
        migrations.AddField(
            model_name='channel',
            name='subscriber',
            field=models.PositiveIntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)]),
        ),
    ]
